### ISSUE TITLE
Details on the Wifi/Camera?

### ISSUE THREAD

**Issue by mcowger** [HexAirbot/HexNanoMWC_HEX#10]
I'm looking to use the wifi/camera components in another project.  Any details on those?

**Comment by extremeshok** [comment]
Would be nice if they released an app for iOS that was just the camera functionality... 

And allowed the camera to be used as a standard network camera.

Then we would have some use for the useless non flying copter

**Comment by mcowger** [comment]
Thats why i'm hoping to get some details about the camera.

On Tue, Aug 25, 2015 at 1:13 PM, eXtremeSHOK <notifications@github.com>
wrote:

> Would be nice if they released an app for iOS that was just the camera
> functionality...
>
> And allowed the camera to be used as a standard network camera.
>
> Then we would have some use for the useless non flying copter
>
> Sent from my iPhone
>
> > On 25 Aug 2015, at 10:09 PM, Matt Cowger <notifications@github.com>
> wrote:
> >
> > I'm looking to use the wifi/camera components in another project. Any
> details on those?
> >
> > —
> > Reply to this email directly or view it on GitHub.
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/HexAirbot/HexNanoMWC_HEX/issues/10#issuecomment-134724393>
> .
>



-- 
-- Matt
